feature:
- head-branch: feature

fix:
- head-branch: fix

release: 
- head-branch: release

chore:
- head-branch: chore

enhancement:
- head-branch: impr

ui/ux:
- changed-files:
  - any-glob-to-any-file:
    - src/components/**
    - src/styles/**
    - src/assets/**
    - public/**
    - static/**

server: 
- changed-files:
  - any-glob-to-any-file: src/firebase/**

devops:
- head-branch: release
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - .husky/**
    - .release-it.json

documentation:
- head-branch: docs
- changed-files:
  - any-glob-to-any-file: '**/*.md'

package:
- head-branch: deps
- changed-files:
  - any-glob-to-any-file: 'pnpm-lock.yaml'
