name: Bug report
description: Report a bug to help COB Chatbot improve!
labels: "bug"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your time helping COB Chatbot improve!

  - type: textarea
    attributes:
      label: Description
      description: Please describe the bug and how did it happen.
      placeholder: It start off with...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Device(s)
      description: Type of device(s) used.
      multiple: true
      options:
        - Mobile
        - PC
    validations:
      required: false

  - type: textarea
    attributes:
      label: Device Version
      description: |
        e.g:
          - **OS**: Windows 10 / Android(is using mobile)
          - **Browser**: Google Chrome
          - **Browser Version**: 128.0.6613.138 (Official Build) (64-bit)
      value: |
        - OS:
        - Browser:
        - Browser Version:
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots or Videos
      description: You can provide screenshots or videos to let us find it quicker.
    validations:
      required: false
